# Generated by Django 3.1.3 on 2020-12-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201205_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
