# Generated by Django 3.1.3 on 2020-12-06 03:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201205_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
