# Generated by Django 3.1.3 on 2020-12-06 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201206_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='body',
            new_name='post_text',
        ),
    ]
